server:
  #   SSL证书
  ssl:
    key-store: classpath:anchwngb.cn.pfx
    key-store-password: g15xrx4u57
    key-store-type: PKCS12

spring:
  data:
    # redis配置
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password: 'eBI6YnFIEQ5'
  # mysql配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/super_bot?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
    username: super_bot
    password: 'hthWC78MHFZ7KACK'


# 管理员 多个使用，隔开
admin: oosXXXXXXM67F2o,

#是否开启文本拦截 (防止GPT乱说话) ，触发敏感词时中断回复并提示
isSensitive: true

#过滤哪些敏感字(需开启文本拦截才生效)
sensitive: "(CHAT|GPT|OPENAI)"

# 是否开启GPT-4 如果关闭 则前端的选择模型将无效 最终都会指向GPT-3.5 (如果当前KEY不支持GPT-4 请不要开启 否则用户选择GPT-4则会报错)
enable-gpt: false

# 微信
we-chat:
  # APPID
  appId: 'wx2XXXXXX7eed'
  # 密钥
  secret: 'c82XXXXXXd8aff6bae'
  # 通知模板
  template: '1I4cXXXXXXavLS-xu9t1QuT5Irezvaw'
  # 环境 (develop开发板 trial体验版 release正式版)
  env: 'release'

# 百度翻译
baidu-translation:
  # 百度翻译Appid
  appid: '202XXXXXX2'
  # 百度翻译密码要
  secret: '2WibXXXXXXPTBG8'

# 阿里OSS
ali-oss:
  endpoint: 'osXXXXXXi.aliyuncs.com'
  accessKey: 'LXXXXXXh48n'
  secretKey: 'WDqmXXXXXXMUtCrI'
  bucketName: 'sea-time'
  domain: 'https://sea-XXXXXXncs.com'

# GPT 对话助手配置
gpt:
  # 开发者名称
  author: '时间海'
  # BOT 中文名
  botNameChinese: '时间海的助手'
  # BOT 英文名
  botNameEnglish: 'TIME SEA'

# 支付宝配置
ali-pay:
  # 支付宝应用ID
  appId: '20XXXXXX14'
  # 支付宝公钥
  alipayPublicKey: 'MIIBXXXXXXVxE83NK2kJ9X8JvoukY/GVXXXXXXM79uzDC2lyNbCVPFsHhJLE3Q5R49kjvlnUca2rYYcjZGFk5WlqBx8vhd2YrScqp243OWuQQeFvwOH0iShAJrtZQ6iRW/roFt/WSrVd3U3B33C7BHnor+Ffoa+P7ROUqICYJCpBfhZYDqs9mWYtQMIHQN+xLuFAG2uUbw1LVm7diTEDGatra/OCTBVW63VfiNpcAi+F9TcSsamIqh1Jl+mbL+RFIuTRXWwccsmo/x5ABvl/AWk5IGoUxsv0btBzf5VgwIDAQAB'
  # 私钥
  privateKey: 'MIIEvwIXXXXXXSCBKkwggSlAgEAAoIBAQCJl8XqlEHjukFJNCajxDF9XETzc0raQn1fwm+i6Rj8ZV6kf/T9asKSmn/O9hMdU225s+KQrdkLwWLOhk0gGczv27MMLaXI1sJU8WweEksTdDlHj2SO+WdRxrathhyNkYWTlaWoHHy+F3ZitJyqnbjc5a5BB4W/A4fSJKEAmu1lDqJFb+ugW39ZKtV3dTcHfcLsEeeiv4V+hr4/tE5SogJgkKkF+FlgOqz2ZZi1AwgdA37Eu4UAba5RvDUtWbt2JMQMZq2tr84JMFVbrdV+I2lwCL4X1NxKxqYiqHUmX6Zsv5EUi5NFdbBxyyaj/HkAG+X8BaTkgahTGy/Ru0HN/lWDAgMBAAECggEAHxlz/aKHBg8KRJ6KAUgOG5SobRJpH84ZgnRzQTJImHvdGXdmi4T+953+N2w9Q8qgqXG0SxlQTqzmRWHrus66GJji7mS+7RdFk2eCFYXy/DGv5LHPe9V5ee1dSvleKM10kLgpWkceFuU8t/C03IeLyjoL2dz2aQdGQsROs9FQyR9gYvgr/GTNLB+VmIBNSEdM1kQzYIreCwk8KsqnZ6I3dDqcfGBtiVhHxwV4dgTn/V46X8MGxASFGXZEFyd3HNCTttme2SvkHRcF46cvZD48VqJaH96t9PmKHgWx09fN9v0+GDuMTuDsjvJT/DF73kjR1vWWS4BuA3RHHZoz1DmbaQKBgQDhMjXykEVLWDt/7sVrawL1MDux44JEv6Ypr8TLAzUDOv3NNanZex4j0+1YHOYclaWE7nZZPo6nAX78+Uo1egddRmZnt31XmpUZK9bPDlpmSELL7OSbw3rzbNlooEuOcpA7j3V7IUFuuVNGXpOhypMTE09e5ypnJRWVHJC8V6VhPQKBgQCcaevS7cA2/qhpxRJ64F7+pk12dKmnTKM+GW9qG6NHPXTYM7KU8tHA/DhaHIWvH39wRYIdp4LTkjLbpn5DOBs/1FblfxxNUXdkcUk5f3duQUCeXOeLfK0HhWeipOqIkudEJKQXlL3DUkf0NKex1Pem5TJEqEhzxDunJyLbn6B9vwKBgQDN/q0khl4srrg2rYa/XPMmsAlbDt8B3kG0Dkm43uUmYFb72SPWge2vHlQU7tJ7wVPYRn3R4wyArjioVa1RP5/u7dAM/ebVNN1AWj6zxtBgkacwfTEdXvJgK+iv8TlMQ3W2VeNET8ZX74TCcQ8gx3pDz70h9dlu4phcfvXSo2XvjQKBgQCFNy1Tu4xPCntTgjYoEzq09dzZu6jWxU3vUOh0Xc+lmDERBo7djyWYkPhJvysYqOH4NCsKqKWjHkxUiSvWgk2rAmV0Ftt6+pyOHnI4F1kXvVmUxxmp0mjoE/XdL0pVQZDYl8BuGQ+58DU6RzJgIjs+mMxEb3Mtrf8EcS+eEAk3rwKBgQCTrlGkrNKO5+NGup03WSXd8bRGw6Q1jFXtDhA6JqwDPFbhmTS1VnCeOX6fPBvlUpdEZYrozdRNFoq0grjEZnlNcJB4f/9q9iBVTOnMdAQLIrbPccMdoijjQcHVkXEHPIEchsLahXcuqbQLhOEUt4fkQ/k1YB+IZb8wcCQLGrVZ1Q=='
  # 域名
  domain: 'https://XXXXXX8.zicp.fun'

# 初始化配置(只加载一次)

config:
  # OPEN AI API
  openAiUrl: 'https://chatgpt1.nextweb.fun/api/proxy/v1'
  # SD API
  sdUrl: 'http://127.0.0.1:7860'
  # MJ API
  mjUrl: 'http://127.0.0.1:7860'
  #OPEN
  openKey: 'sk-NXXXXXX1exF1MtLxEaFhKU'
  # 用户第一次登录奖励次数
  incentiveFrequency: 10
  # 观看视频奖励次数
  videoFrequency: 1
  # SD图生图消耗次数
  sdImage2Frequency: 5
  # GPT文生图消耗次数
  gptTextImageFrequency: 5
  # SD文生图消耗次数
  sdTextImageFrequency: 5
  # MJ文生图消耗次数
  mjTextImageFrequency: 5
  # MJ图生图消耗次数
  mjImage2Frequency: 5
  #GPT消耗次数
  gptFrequency: 1
  # 观看视频奖励次数
  signInFrequency: 1


